name: proxmox_client
description: A Proxmox client to interact with pve
version: 0.0.0

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.19.1
  dart_mappable: ^4.3.0
  http: ^1.2.2

dev_dependencies:
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.3.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
